# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-03-28 17:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0002_qoate'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Qoate',
            new_name='Quote',
        ),
    ]
