# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-03-28 18:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0003_auto_20180328_1758'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quote',
            name='users',
            field=models.ManyToManyField(related_name='quotes', to='first_app.User'),
        ),
    ]
